/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modules.admin;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;
import javax.swing.JPanel;
import modules.admin.author.AuthorPanel;
import modules.admin.bookcopy.BookCopyPanel;
import modules.admin.books.BookPanel;
import modules.admin.borrow.BorrowPanel;
import modules.admin.member.MemberPanel;
import modules.admin.publisher.PublisherPanel;
import modules.admin.returning.ReturningPanel;

/**
 *
 * @author fdn-azhar
 */
public class AdminHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomeScreen
     */
    public AdminHomeScreen() {
        initComponents();
        
        GraphicsDevice gd =
            GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();

        if (gd.isFullScreenSupported()) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        } else {
            System.err.println("Full screen not supported");
            setSize(1024, 768); // just something to let you see the window
            setVisible(true);
        }
        
        executeButtonAction(btnMenuBorrowing);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMenuAuthors = new javax.swing.JButton();
        btnMenuMembers = new javax.swing.JButton();
        btnMenuPublishers = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnMenuBorrowing = new javax.swing.JButton();
        btnMenuReturn = new javax.swing.JButton();
        btnMenuBookCopy = new javax.swing.JButton();
        btnMenuBooks = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(646, 54));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 1));
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 1));
        jSeparator1.setSize(new java.awt.Dimension(50, 1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(138, 178, 166));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/circle-user.png"))); // NOI18N
        jButton1.setText("Azhar Fajriansyah");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(499, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(62, 63, 91));

        jPanel2.setBackground(new java.awt.Color(62, 63, 91));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Public Library");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Data Master");

        btnMenuAuthors.setBackground(new java.awt.Color(62, 63, 91));
        btnMenuAuthors.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnMenuAuthors.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuAuthors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/user.png"))); // NOI18N
        btnMenuAuthors.setText("Authors");
        btnMenuAuthors.setContentAreaFilled(false);
        btnMenuAuthors.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenuAuthors.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAuthorsActionPerformed(evt);
            }
        });

        btnMenuMembers.setBackground(new java.awt.Color(62, 63, 91));
        btnMenuMembers.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnMenuMembers.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/users-alt.png"))); // NOI18N
        btnMenuMembers.setText("Members");
        btnMenuMembers.setContentAreaFilled(false);
        btnMenuMembers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMembersActionPerformed(evt);
            }
        });

        btnMenuPublishers.setBackground(new java.awt.Color(62, 63, 91));
        btnMenuPublishers.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnMenuPublishers.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuPublishers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/company.png"))); // NOI18N
        btnMenuPublishers.setText("Publishers");
        btnMenuPublishers.setContentAreaFilled(false);
        btnMenuPublishers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuPublishers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPublishersActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Transaction");

        btnMenuBorrowing.setBackground(new java.awt.Color(62, 63, 91));
        btnMenuBorrowing.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnMenuBorrowing.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuBorrowing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/shopping-cart-add.png"))); // NOI18N
        btnMenuBorrowing.setText("Borrow");
        btnMenuBorrowing.setContentAreaFilled(false);
        btnMenuBorrowing.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuBorrowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBorrowingActionPerformed(evt);
            }
        });

        btnMenuReturn.setBackground(new java.awt.Color(62, 63, 91));
        btnMenuReturn.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnMenuReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/undo.png"))); // NOI18N
        btnMenuReturn.setText("Return");
        btnMenuReturn.setContentAreaFilled(false);
        btnMenuReturn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuReturnActionPerformed(evt);
            }
        });

        btnMenuBookCopy.setBackground(new java.awt.Color(62, 63, 91));
        btnMenuBookCopy.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnMenuBookCopy.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuBookCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/books.png"))); // NOI18N
        btnMenuBookCopy.setText("Book Copy");
        btnMenuBookCopy.setContentAreaFilled(false);
        btnMenuBookCopy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuBookCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBookCopyActionPerformed(evt);
            }
        });

        btnMenuBooks.setBackground(new java.awt.Color(62, 63, 91));
        btnMenuBooks.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnMenuBooks.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/books.png"))); // NOI18N
        btnMenuBooks.setText("Books");
        btnMenuBooks.setContentAreaFilled(false);
        btnMenuBooks.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenuBorrowing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuAuthors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuPublishers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnMenuBookCopy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuBorrowing, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuPublishers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuBookCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pnlContent.setBackground(new java.awt.Color(246, 241, 222));

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAuthorsActionPerformed
        executeButtonAction(btnMenuAuthors);
    }//GEN-LAST:event_btnMenuAuthorsActionPerformed

    private void btnMenuMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMembersActionPerformed
        executeButtonAction(btnMenuMembers);
    }//GEN-LAST:event_btnMenuMembersActionPerformed

    private void btnMenuPublishersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPublishersActionPerformed
        executeButtonAction(btnMenuPublishers);
    }//GEN-LAST:event_btnMenuPublishersActionPerformed

    private void btnMenuBorrowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBorrowingActionPerformed
        executeButtonAction(btnMenuBorrowing);
    }//GEN-LAST:event_btnMenuBorrowingActionPerformed

    private void btnMenuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuReturnActionPerformed
        executeButtonAction(btnMenuReturn);
    }//GEN-LAST:event_btnMenuReturnActionPerformed

    private void btnMenuBookCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBookCopyActionPerformed
        executeButtonAction(btnMenuBookCopy);
    }//GEN-LAST:event_btnMenuBookCopyActionPerformed

    private void btnMenuBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBooksActionPerformed
        executeButtonAction(btnMenuBooks);
    }//GEN-LAST:event_btnMenuBooksActionPerformed

    private void executeButtonAction(javax.swing.JButton button) {
        if (!button.isSelected()) {
            resetButtonsState();
            button.setSelected(true);
            button.setContentAreaFilled(true);
            
            if (button == btnMenuAuthors) {
                setMainContentTo(new AuthorPanel());
            } else if (button == btnMenuPublishers) {
                setMainContentTo(new PublisherPanel());
            } else if (button == btnMenuMembers) {
                setMainContentTo(new MemberPanel());
            } else if (button == btnMenuBooks) {
                setMainContentTo(new BookPanel());
            } else if (button == btnMenuBookCopy) {
                setMainContentTo(new BookCopyPanel());
            } else if (button == btnMenuBorrowing) {
                setMainContentTo(new BorrowPanel());
            } else if (button == btnMenuReturn) {
                setMainContentTo(new ReturningPanel());
            } else {
                setMainContentTo(new JPanel());
            }
        }
    }
    
    private void resetButtonsState() {
        btnMenuBorrowing.setSelected(false);
        btnMenuReturn.setSelected(false);
        btnMenuAuthors.setSelected(false);
        btnMenuPublishers.setSelected(false);
        btnMenuBooks.setSelected(false);
        btnMenuBookCopy.setSelected(false);
        btnMenuMembers.setSelected(false);
        
        btnMenuBorrowing.setContentAreaFilled(false);
        btnMenuReturn.setContentAreaFilled(false);
        btnMenuAuthors.setContentAreaFilled(false);
        btnMenuPublishers.setContentAreaFilled(false);
        btnMenuBooks.setContentAreaFilled(false);
        btnMenuBookCopy.setContentAreaFilled(false);
        btnMenuMembers.setContentAreaFilled(false);
    }
    
    private void setMainContentTo(javax.swing.JPanel panel) {
        pnlContent.setLayout(new java.awt.BorderLayout());
        pnlContent.removeAll();
        pnlContent.add(panel);
        pnlContent.validate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminHomeScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuAuthors;
    private javax.swing.JButton btnMenuBookCopy;
    private javax.swing.JButton btnMenuBooks;
    private javax.swing.JButton btnMenuBorrowing;
    private javax.swing.JButton btnMenuMembers;
    private javax.swing.JButton btnMenuPublishers;
    private javax.swing.JButton btnMenuReturn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
