/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package modules.admin.member;

import com.github.lgooddatepicker.components.DatePicker;
import data.models.Member;
import data.repository.MemberRepository;
import helpers.AFDialog;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import modules.shared.RegularDataTablePanel;
import modules.shared.RegularDataTablePanelInterface;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Azhar
 */
public class MemberPanel extends javax.swing.JPanel implements RegularDataTablePanelInterface {
    
    ArrayList<Member> members;
    Member editedMember;
    RegularDataTablePanel regularDataTablePanel;
    DatePicker datePicker;
    MemberRepository repository = new MemberRepository();

    /**
     * Creates new form MemberPanel
     */
    public MemberPanel() {
        initComponents();
        
        datePicker = new DatePicker();
        pnlMembershipDate.setLayout(new java.awt.BorderLayout());
        pnlMembershipDate.removeAll();
        pnlMembershipDate.add(datePicker);
        pnlMembershipDate.validate();
        validate();
        
        regularDataTablePanel = new RegularDataTablePanel(this);
        
        String[] column = {"First Name", "Last Name", "Email", "Phone Number", "Membership Date", "Membership Status", "Address"};
        regularDataTablePanel.setupTableColumn(column);
        
        pnlDataTable.setLayout(new java.awt.BorderLayout());
        pnlDataTable.removeAll();
        pnlDataTable.add(regularDataTablePanel);
        pnlDataTable.validate();
        
        new Thread(regularDataTablePanel::populateData).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDataTable = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        textFieldEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaAddress = new javax.swing.JTextArea();
        pnlMembershipDate = new javax.swing.JPanel();
        comboBoxMembershipStatus = new javax.swing.JComboBox<>();
        textFieldFirstName = new javax.swing.JTextField();
        textFieldPhoneNumber = new javax.swing.JTextField();

        setBackground(new java.awt.Color(246, 241, 222));

        pnlDataTable.setBackground(new java.awt.Color(246, 241, 222));

        javax.swing.GroupLayout pnlDataTableLayout = new javax.swing.GroupLayout(pnlDataTable);
        pnlDataTable.setLayout(pnlDataTableLayout);
        pnlDataTableLayout.setHorizontalGroup(
            pnlDataTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDataTableLayout.setVerticalGroup(
            pnlDataTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(246, 241, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Member");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("Email");

        btnSave.setBackground(new java.awt.Color(138, 178, 166));
        btnSave.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        textFieldEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Last Name");

        textFieldLastName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("Phone Number");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("Membership Date");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("Membership Status");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setText("Address");

        textAreaAddress.setColumns(20);
        textAreaAddress.setRows(5);
        textAreaAddress.setPreferredSize(new java.awt.Dimension(300, 89));
        jScrollPane1.setViewportView(textAreaAddress);

        pnlMembershipDate.setBackground(new java.awt.Color(246, 241, 222));
        pnlMembershipDate.setPreferredSize(new java.awt.Dimension(300, 24));
        pnlMembershipDate.setSize(new java.awt.Dimension(300, 24));

        javax.swing.GroupLayout pnlMembershipDateLayout = new javax.swing.GroupLayout(pnlMembershipDate);
        pnlMembershipDate.setLayout(pnlMembershipDateLayout);
        pnlMembershipDateLayout.setHorizontalGroup(
            pnlMembershipDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pnlMembershipDateLayout.setVerticalGroup(
            pnlMembershipDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        comboBoxMembershipStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        comboBoxMembershipStatus.setMinimumSize(new java.awt.Dimension(300, 24));
        comboBoxMembershipStatus.setPreferredSize(new java.awt.Dimension(300, 24));
        comboBoxMembershipStatus.setSize(new java.awt.Dimension(300, 24));

        textFieldFirstName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        textFieldPhoneNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(textFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(pnlMembershipDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(comboBoxMembershipStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(283, 283, 283)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlMembershipDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxMembershipStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClear))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlDataTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDataTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String firstName = textFieldFirstName.getText();
        String lastName = textFieldLastName.getText();
        String email = textFieldEmail.getText();
        String phoneNumber = textFieldPhoneNumber.getText();
        String membershipDate = datePicker.getDateStringOrEmptyString();
        String membershipStatus = comboBoxMembershipStatus.getSelectedItem().toString();
        String address = textAreaAddress.getText();

        // Fields validation
        if (firstName.isEmpty()) {
            AFDialog.showError(this, "Please fill the first name field.");
            return;
        } else if (lastName.isEmpty()) {
            AFDialog.showError(this, "Please fill the last name field.");
            return;
        } else if (email.isEmpty()) {
            AFDialog.showError(this, "Please fill the email field.");
            return;
        } else if (phoneNumber.isEmpty()) {
            AFDialog.showError(this, "Please fill the phone number field.");
            return;
        } else if (membershipDate.isEmpty()) {
            AFDialog.showError(this, "Please fill the membership date field.");
            return;
        } else if (membershipStatus.isEmpty()) {
            AFDialog.showError(this, "Please fill the membership status field.");
            return;
        } else if (address.isEmpty()) {
            AFDialog.showError(this, "Please fill the address field.");
            return;
        }

        if (editedMember != null) {
            saveData(false, editedMember.id, firstName, lastName, email, phoneNumber, address, membershipDate, membershipStatus);
        } else {
            saveData(true, 0, firstName, lastName, email, phoneNumber, address, membershipDate, membershipStatus);
        }
        regularDataTablePanel.populateData();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        setDataForm(null);
    }//GEN-LAST:event_btnClearActionPerformed

    public void setDataForm(Member member) {
        this.editedMember = member;
        if (member != null) {
            textFieldFirstName.setText(member.firstName);
            textFieldLastName.setText(member.lastName);
            textFieldEmail.setText(member.email);
            textFieldPhoneNumber.setText(member.phoneNumber);
            datePicker.setDate(LocalDate.parse(member.membershipDate));
            comboBoxMembershipStatus.setSelectedIndex((member.membershipStatus.equals("Active")) ? 0 : 1);
            textAreaAddress.setText(member.address);
        } else {
            clearForm();
        }
    }
    
    private void saveData(boolean isNewData, int id, String firstName, String lastName, String email, String phoneNumber, String address, String membershipDate, String membershipStatus) {
        Member member = new Member(id, firstName, lastName, email, phoneNumber, address, membershipDate, membershipStatus);
        try {
            if (isNewData) {
                repository.save(member);
                AFDialog.showMessage(this, "Member saved successfully.");
            } else {
                repository.update(member);
                AFDialog.showMessage(this, "Publisher updated successfully.");
            }
            setDataForm(null);
        } catch (Exception e) {
            AFDialog.showError(this, e.getLocalizedMessage());
        }
    }
    
    private void clearForm() {
        textFieldFirstName.setText("");
        textFieldLastName.setText("");
        textFieldEmail.setText("");
        textFieldPhoneNumber.setText("");
        datePicker.setText("");
        comboBoxMembershipStatus.setSelectedIndex(0);
        textAreaAddress.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboBoxMembershipStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDataTable;
    private javax.swing.JPanel pnlMembershipDate;
    private javax.swing.JTextArea textAreaAddress;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldFirstName;
    private javax.swing.JTextField textFieldLastName;
    private javax.swing.JTextField textFieldPhoneNumber;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onEditClicked(int row) {
        setDataForm(members.get(row));
    }

    @Override
    public void onDeleteClicked(int row) {
        String id = String.valueOf(members.get(row).id);
        
        try {
            repository.delete(id);
            regularDataTablePanel.populateData();
        } catch (Exception ex) {
            AFDialog.showError(this, ex.getLocalizedMessage());
        }
    }

    @Override
    public ArrayList<Object[]> provideData(String query) {
        members = new ArrayList<>();
        members = repository.populate(query);
        ArrayList<Object[]> data = new ArrayList<>();
        for(Member obj : members) {
            data.add(new Object[] {obj.firstName, obj.lastName, obj.email, obj.phoneNumber, obj.membershipDate, obj.membershipStatus, obj.address});
        }
        return data;
    }

    @Override
    public void onPrintClicked() {
        try {
            String path = "src/modules/admin/member/MemberReport.jasper";
            HashMap params = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, params, repository.connection);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            AFDialog.showError(this, ex.getLocalizedMessage());
        }
    }
}
